### ISSUE TITLE
searchbox don't return anything but python error in term

### ISSUE THREAD

**Issue by AppleSeed2010** [toroettg/SeriesMarker#1] opened 2015-09-07 18:34 UTC
Version 0.0.3
On the add window, the search button return an error :

>[ERROR   ] error           - Show has no attribute named _load_banners
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pytvdbapi/api.py", line 161, in __getattr__
    return self.data[item]
  File "/usr/lib/python3.4/site-packages/pytvdbapi/utils.py", line 89, in __getitem__
    return self._data[self.__transform__(item)]
KeyError: '_load_banners'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/seriesmarker/gui/search_dialog.py", line 69, in on_search_button_clicked
    show._load_banners()
  File "/usr/lib/python3.4/site-packages/pytvdbapi/api.py", line 163, in __getattr__
    raise error.TVDBAttributeError(u"Show has no attribute named {0}".format(item))
pytvdbapi.error.TVDBAttributeError: ('Show has no attribute named _load_banners', (), {})

**Comment by toroettg** [comment] 2016-01-08 20:32
Hello,

this was caused by an API change at pytvdbapi and should be resolved with the latest release (v0.1.0). Thank you for taking the time to report this and I apologize for the late response!

Kind regards,
Tobias

**Closed by toroettg** 2016-01-08 20:32 UTC
